/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.2/samples
 */

 plugins {
    kotlin("jvm") version "1.9.21" // Use the appropriate Kotlin version for your project 
}

repositories {
    mavenCentral() 
}

dependencies {
// https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
implementation("org.xerial:sqlite-jdbc:3.34.0")
}




